### ISSUE TITLE
All tested attacks fails and more

### ISSUE THREAD

**Issue by dkjajhqu2h3j** [CICADA8-Research/RemoteKrbRelay#1]
Hi,

I have really looked forward to a tool like this being released. However, none of the attacks I have tested worked... There are too many errors to write all of them in detail here but as an example I will use the Shadow Credential attack.

Executing `.\RemoteKrbRelay.exe -shadowcred -victim workstation1.adlab1.local -target dc1.adlab1.local -clsid f87b28f1-da9a-4f35-8ec0-800efcf26b83 -debug` it looks like the Kerberos relay part works and the tool claims to have started a session with LDAP. The tool then claims to have generated key credentials but then the attack fails with "LDAP Last status LDAP_OPERATIONS_ERROR". Note that the `-debug` parameter was used here so there is no more information available. 

![shadowcreds1](https://github.com/CICADA8-Research/RemoteKrbRelay/assets/153735386/f3298db8-40e4-46b9-ad21-8e25c3409e79)

Checking if the tool actually has written any Shadow Credentials to the target's attribute `msDS-KeyCredentialLink` using BloodyAD the output is that no Shadow Credentials exists.

![shadowcreds2](https://github.com/CICADA8-Research/RemoteKrbRelay/assets/153735386/c362f2ea-1070-4d45-a5bf-64e9148b18fe)

A question. Building the tool I assumed incorporates all .dll files it needs but that is not the case. For example, if executing the Shadow Credential attack one must copy the file BouncyCastle.Crypto.dll from RemoteKrbRelay-main.zip into the same folder as RemoteKrbRelay.exe or else the tool fails. Is this how it is supposed to work?

Thanks!

**Comment by MzHmO** [comment]
Hi, it looks like Windows is blocking certain actions. Check with the usual KrbRelayUp / KrbRelay. Do they work?

**Comment by dkjajhqu2h3j** [comment]
KrbRelayUp, KrbRelay and DavRelayUp all worked for some time until MS ninja patched it. See https://twitter.com/Geiseric4/status/1583374116941594627 and https://twitter.com/_Imm0/status/1583187655222706177. This is actually the reason why I am so interested in your tool. 

FYI. Writing Shadow Credentials using for example BloodyAD and ntlmrelayx.py works fine so there is nothing wrong with that part. The DC is running Server 2019 and is fully patched.

**Comment by MzHmO** [comment]
I think MS patched the Kerberos relay attack after OXID Resolve. However, you can try to perform the relay during OXID Resolving. Check the [ADCSCoercerPotato](https://github.com/decoder-it/ADCSCoercePotato/) tool in your lab, please. If it works, please let me know. I will complete the functionality of RemoteKrbRelay

**Comment by dkjajhqu2h3j** [comment]
ADCSCoercePotato sort of works for me. However, ntlmrelayx says that the authentication fails.
 
IPs:
DC (DC1) and ADCS (I don't have a second ADCS instance installed elsewhere): 10.0.0.200
Kali (Socat and ntlmrelayx): 10.0.0.220
Attacking Windows workstation (ADCSCoercePotato): 10.0.0.210

Setup:
1) On 10.0.0.220: socat tcp-listen:135,fork,reuseaddr tcp:10.0.0.210:9999
2) On 10.0.0.220: impacket-ntlmrelayx -t http://10.0.0.200/certsrv/certrqus.asp --adcs --template DomainController -smb2support
3) On 10.0.0.210: .\ADCSCoercePotato.exe -m 10.0.0.200 -k 10.0.0.220 -u adlab1_domainuser1 -p [redacted] -d adlab1.local

Result:
In ntlmrelayx, "Authenticating against http://10.0.0.200 as ADLAB1/DC1$ FAILED". This in my mind happens because the NTLM authentication is relayed back to its source which is not possible. The whitepaper claims that ADCSCoercePotato can be used to relay Kerberos authentication but there are no detailed instructions for doing that so I cannot test it.

**Comment by MzHmO** [comment]
That's great, yeah. I know how to rewrite the instrument. It can be quite time-consuming as you have to parse the RAW TCP packet. However, this is a workaround to the Kerberos Relay patch. 

In the case of NTLM Relay, if you had ADCS on the other computer, it would work fine.

In the case of Kerberos it is possible to relay it to the same computer, but it takes time to finalize the tool, I'll look into it.

**Comment by MzHmO** [comment]
Hi Friends

There are tools that can retranslate AP-REQ from RAW TCP

https://github.com/dirkjanm/krbrelayx

https://github.com/decoder-it/KrbRelay-SMBServer

https://github.com/decoder-it/KrbRelayEx
